'use client'

import { useEffect, useMemo, useState } from 'react'
import { useReactTable, getCoreRowModel, flexRender, type ColumnDef } from '@tanstack/react-table'
import { useLeadsStore, type Lead, type Environment } from '@/lib/leads-store'
import { ChevronDown, ChevronLeft, ChevronRight, ChevronsUpDown, Loader2, Moon, Search, SlidersHorizontal, Sun, Users, X } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Line, LineChart, XAxis, YAxis } from 'recharts'
import { ChartContainer, ChartTooltip, ChartTooltipContent, type ChartConfig } from '@/components/ui/chart'

type TimeRange = 'Yesterday' | 'Today' | 'Last 3 days' | 'Last 7 days' | 'Last 11 days'

const environments: Environment[] = ['Dev', 'UAT', 'Prod']
const timeRanges: TimeRange[] = ['Yesterday', 'Today', 'Last 3 days', 'Last 7 days', 'Last 11 days']
const statuses = ['All statuses', 'New', 'Contacted', 'Qualified', 'Disqualified']
const dynamicFields = ['campaign', 'region', 'interest']
const submissionsByDay = Array.from({ length: 31 }, (_, index) => ({ day: String(index + 1), submissions: [8, 12, 16, 10, 24, 18, 15, 22, 28, 20, 31, 26, 35, 30, 27, 39, 34, 42, 36, 45, 40, 48, 43, 52, 47, 56, 51, 59, 54, 63, 58][index] }))
const dailyActivity = submissionsByDay.map((item, index) => ({ ...item, submissions: Math.max(4, item.submissions - 8 + (index % 4) * 3) }))
const chartConfig = { submissions: { label: 'Submissions', color: 'var(--chart-1)' } } satisfies ChartConfig

function getRangeDates(range: TimeRange) {
  const end = new Date('2026-08-23T16:42:00Z'); const days = range === 'Yesterday' ? 1 : range === 'Today' ? 0 : Number(range.split(' ')[1]); const start = new Date(end)
  if (range === 'Yesterday') { start.setUTCDate(start.getUTCDate() - 1); start.setUTCHours(0, 0, 0, 0); end.setUTCHours(0, 0, 0, 0) } else { start.setUTCDate(start.getUTCDate() - days); start.setUTCHours(0, 0, 0, 0) }
  return { start, end }
}
function formatDate(value: string) { return new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(value)) }
function statusClass(status: Lead['status']) { return `status-${status.toLowerCase()}` }

export default function Page() {
  const [activeView, setActiveView] = useState<'overview' | 'leads'>('leads'); const [environment, setEnvironment] = useState<Environment>('Prod'); const { leads: apiLeads, loading: apiLoading, fetchLeads } = useLeadsStore(); const [timeRange, setTimeRange] = useState<TimeRange>('Last 7 days'); const [search, setSearch] = useState(''); const [status, setStatus] = useState('All statuses'); const [pageSize, setPageSize] = useState(25); const [page, setPage] = useState(0); const [loading, setLoading] = useState(false); const [dark, setDark] = useState(false); const [showFilters, setShowFilters] = useState(false); const [selectedLead, setSelectedLead] = useState<Lead | null>(null)
  useEffect(() => { fetchLeads(environment, pageSize) }, [environment, pageSize, fetchLeads])
  const dateRange = useMemo(() => getRangeDates(timeRange), [timeRange])
  const sourceLeads = apiLeads
  const filteredLeads = useMemo(() => sourceLeads.filter((lead) => { const haystack = `${lead.firstName} ${lead.lastName} ${lead.email} ${lead.phoneNumber} ${lead.submissionId} ${Object.values(lead.dynamic).join(' ')}`.toLowerCase(); return haystack.includes(search.toLowerCase()) && (status === 'All statuses' || lead.status === status) }), [sourceLeads, search, status])
  const visibleLeads = useMemo(() => filteredLeads.slice(page * pageSize, page * pageSize + pageSize), [filteredLeads, page, pageSize]); const totalPages = Math.max(1, Math.ceil(filteredLeads.length / pageSize))
  const columns = useMemo<ColumnDef<Lead>[]>(() => [{ accessorKey: 'firstName', header: 'First name' }, { accessorKey: 'lastName', header: 'Last name' }, { accessorKey: 'email', header: 'Email' }, { accessorKey: 'phoneNumber', header: 'Phone number' }, { accessorKey: 'submissionId', header: 'Submission ID' }, { accessorKey: 'updatedAt', header: 'Updated at', cell: ({ getValue }) => formatDate(getValue<string>()) }, { accessorKey: 'status', header: 'Status' }, ...dynamicFields.map((field) => ({ id: field, header: field, accessorFn: (row: Lead) => row.dynamic[field] }))], [])
  const coreRowModel = useMemo(() => getCoreRowModel(), [])
  const table = useReactTable({ data: visibleLeads, columns, getCoreRowModel: coreRowModel })
  function changeEnvironment(next: Environment) { setEnvironment(next); setPage(0); setLoading(true); fetchLeads(next, pageSize).finally(() => setLoading(false)) }
  function refresh() { setLoading(true); fetchLeads(environment, pageSize).finally(() => setLoading(false)) }
  const resetPage = () => setPage(0)

  return <div className={dark ? 'app-shell dark' : 'app-shell'}>
    <header className="site-header"><div className="utility-bar"><span>LEADS OPERATIONS</span><nav><a href="#overview" onClick={() => setActiveView('overview')}>OVERVIEW</a><a href="#leads" onClick={() => setActiveView('leads')}>LEADS</a><button onClick={() => setDark(!dark)} aria-label="Toggle dark mode">{dark ? <Sun /> : <Moon />}</button></nav></div><div className="header-main"><div className="wordmark">lead<span>.</span>deck</div><div className="header-controls"><span className="api-label">API STATUS <i /></span><button className="header-env"><span className={`env-dot env-${environment.toLowerCase()}`} />{environment}<ChevronDown /></button></div></div><div className="header-nav"><a className={activeView === 'overview' ? 'active' : ''} href="#overview" onClick={() => setActiveView('overview')}>Overview</a><a className={activeView === 'leads' ? 'active' : ''} href="#leads" onClick={() => setActiveView('leads')}>Leads</a><span className="header-note">Read-only lead viewer</span></div></header>
    <main className="main-content" id="leads"><div className="page-content">
      <div className="page-heading"><div><div className="eyebrow"><span className="live-dot" /> READ-ONLY DATA VIEW</div><h1>Leads</h1><p>Search and inspect submissions across your environments.</p></div><div className="heading-meta"><Users /> <strong>{filteredLeads.length}</strong> records</div></div>{activeView === 'overview' && <section className="overview-grid" id="overview"><div className="chart-card chart-wide"><div className="chart-card-header"><div><span className="eyebrow">MONTHLY SUBMISSION VOLUME</span><h2>Leads submitted this month</h2></div><span className="chart-total">31 days</span></div><ChartContainer config={chartConfig} className="h-[320px] w-full"><BarChart accessibilityLayer data={submissionsByDay} margin={{ left: 4, right: 8, top: 12 }}><CartesianGrid vertical={false} stroke="var(--border)" /><XAxis dataKey="day" tickLine={false} axisLine={false} tickMargin={10} interval={0} /><YAxis tickLine={false} axisLine={false} width={28} label={{ value: 'Submissions', angle: -90, position: 'insideLeft', style: { fill: 'var(--muted-foreground)', fontSize: 11 } }} /><ChartTooltip cursor={false} content={<ChartTooltipContent />} /><Bar dataKey="submissions" fill="var(--color-submissions)" radius={3} /></BarChart></ChartContainer></div><div className="chart-card chart-wide"><div className="chart-card-header"><div><span className="eyebrow">DAILY TREND</span><h2>Submission activity</h2></div><span className="live-badge"><i /> Live</span></div><ChartContainer config={chartConfig} className="h-[280px] w-full"><LineChart accessibilityLayer data={dailyActivity} margin={{ left: 4, right: 8, top: 12 }}><CartesianGrid vertical={false} stroke="var(--border)" /><XAxis dataKey="day" tickLine={false} axisLine={false} tickMargin={10} interval={0} /><YAxis tickLine={false} axisLine={false} width={28} /><ChartTooltip cursor={false} content={<ChartTooltipContent />} /><Line type="monotone" dataKey="submissions" stroke="var(--color-submissions)" strokeWidth={3} dot={false} activeDot={{ r: 5 }} /></LineChart></ChartContainer></div></section>}
      <section className="control-panel" aria-label="Lead query controls"><div className="control-row"><div className="control-title"><strong>Environment</strong><span>Route requests to an API</span></div><div className="environment-tabs">{environments.map((item) => <button key={item} className={environment === item ? 'selected' : ''} onClick={() => changeEnvironment(item)}><span className={`env-dot env-${item.toLowerCase()}`} />{item}{environment === item && <b>✓</b>}</button>)}</div><button className="refresh-button" onClick={refresh} aria-label="Refresh leads">{loading ? <Loader2 className="spin" /> : 'Refresh'}</button></div><div className="control-row"><div className="control-title"><strong>Time window</strong><span>UTC timestamps</span></div><div className="range-tabs">{timeRanges.map((range) => <button key={range} className={timeRange === range ? 'selected' : ''} onClick={() => { setTimeRange(range); resetPage() }}>{range}</button>)}</div><code>{dateRange.start.toISOString().slice(0, 10)} → {dateRange.end.toISOString().slice(0, 10)}</code></div></section>
      {activeView === 'leads' && <section className="table-card"><div className="table-toolbar"><div><h2>All leads <small>{filteredLeads.length}</small></h2><span className="sync-state">{loading ? 'Fetching from' : 'Synced with'} {environment} API</span></div><div className="toolbar-actions"><div className="search-box"><Search /><input value={search} onChange={(e) => { setSearch(e.target.value); resetPage() }} placeholder="Search leads, fields, or IDs" aria-label="Search leads" />{search && <button onClick={() => setSearch('')} aria-label="Clear search"><X /></button>}</div><button className={showFilters ? 'filter-button active' : 'filter-button'} onClick={() => setShowFilters(!showFilters)}><SlidersHorizontal /> Filters {status !== 'All statuses' && <span>1</span>}</button></div></div>
        {showFilters && <div className="filter-drawer"><label>Status<select value={status} onChange={(e) => { setStatus(e.target.value); resetPage() }}>{statuses.map((item) => <option key={item}>{item}</option>)}</select></label><button onClick={() => setStatus('All statuses')}>Clear filter</button></div>}
        <div className="table-wrap">{loading || apiLoading ? <div className="loading-state"><Loader2 className="spin" /><strong>Fetching leads from {environment}</strong><span>Authenticating and requesting the selected UTC window…</span></div> : <table><thead>{table.getHeaderGroups().map((headerGroup) => <tr key={headerGroup.id}>{headerGroup.headers.map((header) => <th key={header.id}>{flexRender(header.column.columnDef.header, header.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map((row) => <tr key={row.id} className="lead-row" onClick={() => setSelectedLead(row.original)} tabIndex={0} onKeyDown={(event) => { if (event.key === 'Enter') setSelectedLead(row.original) }}>{row.getVisibleCells().map((cell) => <td key={cell.id} className={cell.column.id === 'firstName' || cell.column.id === 'lastName' ? 'person' : ''}>{cell.column.id === 'status' ? <span className={`status-pill ${statusClass(cell.getValue<Lead['status']>())}`}><i />{cell.getValue<string>()}</span> : cell.column.id === 'submissionId' ? <code>{flexRender(cell.column.columnDef.cell, cell.getContext()) ?? cell.getValue<string>()}</code> : flexRender(cell.column.columnDef.cell, cell.getContext()) ?? cell.getValue<string>()}</td>)}</tr>)}</tbody></table>}{!loading && !apiLoading && visibleLeads.length === 0 && <div className="empty-state"><Search /><strong>No leads found</strong><span>Try adjusting your search or filters.</span></div>}</div>
        <div className="table-footer"><span>Showing <strong>{filteredLeads.length ? page * pageSize + 1 : 0}–{Math.min((page + 1) * pageSize, filteredLeads.length)}</strong> of <strong>{filteredLeads.length}</strong> leads <em>•</em> continuation token ready</span><div className="pagination"><label>Rows <select value={pageSize} onChange={(e) => { setPageSize(Number(e.target.value)); resetPage() }}><option>25</option><option>50</option><option>100</option></select></label><span>Page {page + 1} of {totalPages}</span><button disabled={!page} onClick={() => setPage(page - 1)} aria-label="Previous page"><ChevronLeft /></button><button disabled={page >= totalPages - 1} onClick={() => setPage(page + 1)} aria-label="Next page"><ChevronRight /></button></div></div></section>}
      {selectedLead && <><button className="drawer-backdrop" aria-label="Close lead details" onClick={() => setSelectedLead(null)} /><aside className="lead-drawer" aria-label="Lead details"><div className="drawer-header"><div><span className="eyebrow">LEAD RECORD</span><h2>{selectedLead.firstName} {selectedLead.lastName}</h2><span className={`status-pill ${statusClass(selectedLead.status)}`}><i />{selectedLead.status}</span></div><button className="icon-button" aria-label="Close lead details" onClick={() => setSelectedLead(null)}><X /></button></div><div className="drawer-section"><span className="drawer-label">Contact information</span><dl><div><dt>Email</dt><dd>{selectedLead.email}</dd></div><div><dt>Phone number</dt><dd>{selectedLead.phoneNumber}</dd></div></dl></div><div className="drawer-section"><span className="drawer-label">Submission</span><dl><div><dt>Submission ID</dt><dd><code>{selectedLead.submissionId}</code></dd></div><div><dt>Updated at</dt><dd>{formatDate(selectedLead.updatedAt)}</dd></div><div><dt>Environment</dt><dd>{environment}</dd></div></dl></div><div className="drawer-section"><span className="drawer-label">Additional fields</span><dl>{Object.entries(selectedLead.dynamic).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></div></aside></>}
      <div className="request-note"><span>Mock request pipeline</span><code>getJwt({environment}) → /getleads?startTime={dateRange.start.getTime()}&endTime={dateRange.end.getTime()}{page ? `&continuationToken=page-${page}` : ''}</code></div>
    </div></main>
  </div>
}
